layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:

  sort_by: pushed
  #- pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: true
    forks: true
    projects:
        # -"pydggrid"
        # "AGILECA"
        # "strapi-plugin-postgis"
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
   linkedin: majidhojati
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
   twitter: MajidGIS
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
   youtube: am22221

topics:
  - name: Global Grid Systems
    web_url: https://github.com/am2222/pydggrid
    image_url: https://github.com/am2222/pydggrid/blob/master/docs/L6kmP.jpg?raw=true

  - name: GIScience  
    web_url: https://scholar.google.com/citations?hl=en&user=QNGs_a4AAAAJ&view_op=list_works&sortby=pubdate
    image_url: https://media.springernature.com/m312/springer-static/image/chp%3A10.1007%2F978-3-030-55092-9_15/MediaObjects/492893_1_En_15_Fig1_HTML.png?as=webp
    
  - name: IPFS and Decentralization
    web_url: https://github.com/ipfs/ipfs
    image_url: https://cluster.ipfs.io/android-chrome-192x192.png
    
  - name: Full stack Developer
    image_url: https://letzgro.net/wp-content/uploads/2016/07/Web-Developer-Skills-1.jpg
