layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:

  sort_by: pushed
  #- pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: true
    forks: true
    projects:
        # -"pydggrid"
        # "mapjfxdxbrowser"
        # "GarbagebinCollector"
        # "SAGASharp"
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
   linkedin: majidhojati
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
   twitter: MajidGIS
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
   youtube: am22221

topics:
  - name: Global Grid Systems
    web_url: https://github.com/am2222/pydggrid
    image_url: https://github.com/am2222/pydggrid/blob/master/docs/L6kmP.jpg?raw=true

  - name: Decentralization 
#     web_url: https://github.com/am2222/pydggrid
    image_url: https://ipfs.io/images/ipfs-illustration-centralized.svg
    
  - name: IPFS
    web_url: https://github.com/ipfs/ipfs
    image_url: https://cluster.ipfs.io/android-chrome-192x192.png
    
  - name: Full stack Developer
    image_url: https://letzgro.net/wp-content/uploads/2016/07/Web-Developer-Skills-1.jpg
